adding new component
adafruit/Wippersnapper_Components pull request #241
Opened 2024-12-22 21:46 UTC by MartinEbnerSensirion

2024-12-22 22:07 UTC, tyeth commented
Thanks @MartinEbnerSensirion, I had planned to look at this over the holidays!
I've got one of these to test, but we'll need the matching driver in the firmware repo too. For now you can fake it by taking over the sen55 and ignoring the old or hard coding the new i2c address in begin

2024-12-22 22:55 UTC, MartinEbnerSensirion commented
@tyeth matching drivers should be quite low-friction as there's a almost 100% compatible [repo here](https://github.com/Sensirion/arduino-i2c-sen66.git)

2024-12-22 23:09 UTC, tyeth commented
Yeah totally! I had too much to finish before the end of the year and it seemed a bit cheeky to prioritise my new sensor when it wasn't available in mass production yet (except the one eval kit model). Didn't stop me starting looking at the Circuitpython port though (did the sen5x last time), but it's shifted dependency to a type heavy repo so more work / verification needed

2024-12-22 23:18 UTC, tyeth requested changes

2024-12-22 23:18 UTC, tyeth commented on components/i2c/sen66/definition.json
> +  "productURL": "https://www.digikey.ch/en/products/detail/sensirion-ag/SEN66-SIN-T/25700945?s=N4IgTCBcDaIM4FMB2A2FIC6BfIA",
If you wouldn't mind changing this to be .com instead of .ch and dropping the query string / attribution bit too (unless your keen to keep it)

2024-12-22 23:24 UTC, tyeth approved these changes
Looks good, thank you

2024-12-22 23:36 UTC, tyeth commented
@MartinEbnerSensirion this'll be merged once there's a corresponding PR for the driver (CI builds for testing). Feel free to have a go (or I'll take it on at some point), and as mentioned you can change the string match of sen55 and then initialisation call, to instead do the sen66 (in src/components/i2c/wippersnapper_i2c), also adding your library requirements to library.properties and platformio.ini (assuming its in arduino library registry which it is - otherwise also the driver git repo to ci build step)

2024-12-22 23:52 UTC, tyeth commented
I see the pr coming along, lets merge this now so we can play sooner

2024-12-22 23:52 UTC, merged

2024-12-23 00:10 UTC, MartinEbnerSensirion commented
@tyeth appreciate it, thanks!