Adding HTU31D sensor definition
adafruit/Wippersnapper_Components pull request #68
Opened 2022-08-23 21:01 UTC by borotaman

Wippersnapper component definition for HTU31D sensor

2022-08-24 21:34 UTC, brentru requested changes
Hi @borotaman - thanks for your first contribution to Adafruit WipperSnapper. I've left two things to fix before we can merge this work in.

2022-08-24 21:34 UTC, brentru commented on components/i2c/htu31d/definition.json
> +      "displayName": "Temperature/Humidity Sensor",
Please make the `displayName` less than 24 characters

Our CI reported this error here: https://github.com/adafruit/Wippersnapper_Components/runs/8004594245?check_suite_focus=true#step:4:27

2022-08-24 21:34 UTC, brentru commented on components/i2c/htu31d/definition.json
> +      "defaultPeriod": 900
Remove this `defaultPeriod`

2023-09-20 11:51 UTC, tyeth commented
Hey @borotaman 
I'm looking at picking up adding this component, unless you wish to carry on with this?

2023-09-28 13:38 UTC, tyeth commented
Closed by this commit https://github.com/adafruit/Wippersnapper_Components/commit/6ab32cedb78f39a6089b41475c366f9e58c9a57c

Component driver code is finished, expect it to be released next wednesday as part of Wippersnapper v1.0.0-beta73

2023-09-28 13:38 UTC, closed without merging